// <auto-generated />
using System;
using Empleados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Empleados.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Empleados.Cuentas", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matricula"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricula");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("Empleados.Empleados", b =>
                {
                    b.Property<Guid>("IdEmpleados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CuentasMatricula")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PuestosidPuestos")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEmpleados");

                    b.HasIndex("CuentasMatricula");

                    b.HasIndex("PuestosidPuestos");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Empleados.Puestos", b =>
                {
                    b.Property<Guid>("idPuestos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nombrePuestos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPuestos");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("Empleados.Empleados", b =>
                {
                    b.HasOne("Empleados.Cuentas", "Cuentas")
                        .WithMany("Empleados")
                        .HasForeignKey("CuentasMatricula");

                    b.HasOne("Empleados.Puestos", "Puestos")
                        .WithMany("Empleados")
                        .HasForeignKey("PuestosidPuestos");

                    b.Navigation("Cuentas");

                    b.Navigation("Puestos");
                });

            modelBuilder.Entity("Empleados.Cuentas", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Empleados.Puestos", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
